{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tlsSecretName }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: alatyr-server
                port:
                  number: 8090
          - path: /swagger
            pathType: Prefix
            backend:
              service:
                name: alatyr-server
                port:
                  number: 8090
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "chart.fullname" . }}-frontend
                port:
                  number: 8080
{{- end }}
